[fix] Add 'node' types to fix error TS2584: Cannot find name 'console'. Do you need to change your target library? Try changing the 'lib' compiler option to include ' dom'.